### ISSUE TITLE
MissingSchema: Invalid URL '/api/ssotap/sync': No scheme supplied

### ISSUE THREAD

**Issue by Rich2020** [rubin-dp0/Support#60] opened 2023-11-06 17:26 UTC
When I try to use the API, I always get the above (title) error. Here is a sample of code for which I get the error:

```
from lsst.rsp import get_tap_service
service = get_tap_service("ssotap")
assert service is not None
query = "SELECT * FROM tap_schema.schemas"
results = service.search(query).to_table()
print(results)
```

I have an access token, but I have no idea where/how to use it. Not sure if that is relevant, however.

Would appreciate a hand. Thanks!

**Comment by MelissaGraham** [comment] 2023-11-06 17:37
Hi @Rich2020, thanks for submitting this issue. I could not reproduce the problem, so I think we're going to need some more information. 

When using the TAP service in the Notebook Aspect of the Rubin Science Platform at data.lsst.cloud, those lines of code execute fine:
![Screen Shot 2023-11-06 at 9 31 51 AM](https://github.com/rubin-dp0/tutorial-notebooks/assets/13826801/cc2d488b-814d-49c9-9919-5bb941e3a34a)

I think we need to know more about what you mean when you say "try to use the API". Maybe are you using, e.g., TOPCAT as demonstrated in the [API Instructions for DP0.2](https://dp0-2.lsst.io/data-access-analysis-tools/api-intro.html)? Some more details and screenshots would be helpful.

**Comment by Rich2020** [comment] 2023-11-06 17:45
@MelissaGraham Thanks for the quick reply. I am not doing this in a Notebook: I am executing my code from the command line on on Mac using Python 3.10 ad lsst-rsp 0.3.5.

**Comment by MelissaGraham** [comment] 2023-11-06 17:53
Thanks for the update.

I think these draft instructions for using `pyvo` to access the TAP service from your laptop might be what you need:
https://dp0-2.lsst.io/v/PREOPS-1284/data-access-analysis-tools/api-intro.html#use-of-pyvo-with-the-rsp-tap-service

The instructions are not yet released and, as you'll see, there are some comments in there, etc. in there. It's a bit rough, but, let us know if they fix the issue?

**Comment by Rich2020** [comment] 2023-11-06 18:05
@MelissaGraham Thank you! That document was the missing key!
For reference, I was trying to use the token as described in the notebook, which did not work: notebooks/system-test/token-info.ipynb

**Comment by MelissaGraham** [comment] 2023-11-06 18:11
Ah I see, and that NB executes fine in the Notebook Aspect too (all notebooks are designed for that).

Glad the `pyvo` instructions were helpful! We'll be getting those released into the main branch of our documentation asap.

I'm going to close this ticket but please feel free to open a new one here in the Support repo if new issues are encountered.

**Closed by MelissaGraham** 2023-11-06 18:11 UTC
