### ISSUE TITLE
[RSP] Institute Confirmation Letter Missing

### ISSUE THREAD

**Issue by jhoonkim** [rubin-dp0/Support#70] opened 2024-06-26 02:02 UTC
I cannot locate the institute confirmation email, even in my spam folder.
There is a big chance that I already deleted it if it was headed to the spam folder.

My ORCID id is 0000-0002-1418-3309.

Thank you.

**Comment by MelissaGraham** [comment] 2024-06-26 03:12
Hi @jhoonkim, thanks for submitting this ticket.

I can see your petition for an RSP account in our system, as "pending confirmation". However, I can't figure out how to resend the email in this case, so I've assigned this issue to @frossie.

@frossie, Ji Hoon Kim's petition can be found under "My Population" but not on the list of "CO Petitions -- Pending Confirmation" (i.e., the lists that are regularly reviewed). I can't navigate my way to a "resend confirmation" button. Can you help here?

**Comment by athornton** [comment] 2024-06-26 03:15
Actually, I had the same problem, and I assumed that the LSST Exchange server just blocked the email for some reason.  Since I can also get in through GitHub, I gave up and forgot about it until I saw this.  Can you see whether I am in the same state and do the same?

**Comment by jhoonkim** [comment] 2024-06-26 03:29
Dear all,
Thank you for replying.
It may be due to the fact that I tried to create an account multiple times
with my institute email ***@***.***) and my personal account (
***@***.***) with the same ORCID ID.

I am willing to expunge or ask you to expunge both of them and start from
scratch if it helps.
Of course, I will surely use my institute email this time.

Let me know which is better.

Thank you very much.

Best,
Ji Hoon

---------------------------------------------------------------------------------------
Ji Hoon Kim, Ph. D.
Associate Research Professor, SNU Astronomy Research Center
Department of Physics and Astronomy,  Seoul National University
ORCID/0000-0002-1418-3309
---------------------------------------------------------------------------------------

**Comment by MelissaGraham** [comment] 2024-06-26 16:51
@athornton it looks like your petition at data.lsst.cloud was approved in March 2023, your account status is "Active". You should be able to log in via GitHub or ORCID, yes? I can also see a gmail is verified and an lsst.org email is unverified. For the latter, I have resent the verification email. This is the action you were hoping for right?

@jhoonkim I actually can only find one account for you, and it is in the stage of needing one confirmed email address. I have also resent the verification email to your @snu.acc.kr email address. If that doesn't work, we'll expunge and have you start over.

Thanks both!

**Comment by MelissaGraham** [comment] 2024-06-26 16:53
@frossie  Re. "_I can't navigate my way to a "resend confirmation" button._" -- I found that there is a "Verify" button I can get to for individual email addresses, when they are unverified, and that clicking it resends the verification email. Previously I'd only used a "Resend" button.

**Comment by jhoonkim** [comment] 2024-06-27 00:52
Hello Melissa,
I can't find one in my email folders, even in the spam.
Can you confirm the email address is ***@***.*** ?
Not @snu.acc.kr.

Thank you very much.

Best,
Ji Hoon

---------------------------------------------------------------------------------------
Ji Hoon Kim, Ph. D.
Associate Research Professor, SNU Astronomy Research Center
Department of Physics and Astronomy,  Seoul National University
ORCID/0000-0002-1418-3309
---------------------------------------------------------------------------------------

**Comment by MelissaGraham** [comment] 2024-06-27 16:10
@jhoonkim  The email address of the only account I can see for you was indeed @snu.acc.kr. That account has been expunged, so you can start the process over, with apologies for the inconvenience.

**Comment by MelissaGraham** [comment] 2024-06-28 16:26
Excellent. I just approved your petition. You should have got an email about that, and another from me welcoming you to Data Preview 0. You should also be able to log in at data.lsst.cloud. Once you can log in, if you can confirm and close this ticket, that would be great!

**Comment by jhoonkim** [comment] 2024-07-01 01:27
Thank you, Melissa.
I confirmed that my account is approved.

I really appreciate it.

Best,
Ji Hoon

---------------------------------------------------------------------------------------
Ji Hoon Kim, Ph. D.
Associate Research Professor, SNU Astronomy Research Center
Department of Physics and Astronomy,  Seoul National University
ORCID/0000-0002-1418-3309
---------------------------------------------------------------------------------------

**Closed** 2024-07-01 01:28 UTC
Labels: RSP Authentication

**Comment by athornton** [comment] 2024-07-01 01:39
> @athornton it looks like your petition at data.lsst.cloud was approved in March 2023, your account status is "Active". You should be able to log in via GitHub or ORCID, yes? I can also see a gmail is verified and an lsst.org email is unverified. For the latter, I have resent the verification email. This is the action you were hoping for right?

It is.  This email never arrived either, and is not in my Junk Mail or Deleted Items folder.  I presume it's the LSST Exchange Server hating CoManage for some reason.
