### ISSUE TITLE
[BUG] Login difficulties

### ISSUE THREAD

**Issue by aibsen** [rubin-dp0/Support#47] opened 2023-05-15 13:02 UTC
**Describe the bug**
I can't log in to the RSP even though my account request was approved.

**To Reproduce**
I am not sure the bug can be reproduced as it only seems to affect my account, but here are the steps:
1. Go to 'data.lsst.cloud'
2. Click on 'log in'
3. Choose identity provider (University of Edinburgh), click 'log on'
4. Sign in with my institution's credentials

**Expected behavior**
I would expect to be redirected to data.lsst.cloud, now logged in. 

**Screenshots**
![image](https://github.com/rubin-dp0/Support/assets/3902852/79df8cc6-faf7-4fc3-a388-9f537d3e3aaa)

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Browser: chrome (113.0.5672.63), firefox (113.0.5672.63)

**Additional context**
When trying to log in, I get redirected to id.lsst.cloud, to the 'Self sign up with approval' page. If I click on 'Science platform' I appeared not logged in again. If I try to start the process of self sign up again, I get the error 'The specified Source Key is already linked to an existing Org identity'. I tried two different browser, also incognito mode. I have never had a successful login so far.

**Comment by aibsen** [comment] 2023-05-17 11:32
Maybe it is relevant to point out that when I first tried to register in the LSST registry, I got a first email to verify my address, but never got a confirmation email. The system had to then be triggered to resend the invite. Could deleting my account and creating again solve the issue?

**Comment by frossie** [comment] 2023-05-25 18:20
Hi sorry for the delay, you are probably correct as to the cause. I have deleted your registration so try re-enrolling.

**Comment by aibsen** [comment] 2023-05-30 12:28
Thanks! will do

**Comment by lluisa11** [comment] 2023-06-01 04:28
Hi, I am also having this issue. Can I try this?

**Comment by MelissaGraham** [comment] 2023-06-01 14:51
@lluisa11  -- we could try this for you. Can you confirm that completely deleting your account will be ok? And that you do not have anything saved in your home directory at data.lsst.cloud that you want to keep?

**Comment by lluisa11** [comment] 2023-06-01 17:02
Hi Melissa,

I was working on a Notebook for a research project. Would that also be
deleted?

Thank you for your quick response,

Luisa Gonzalez

**Comment by MelissaGraham** [comment] 2023-07-12 21:56
Emailed Luisa today, to see if the issue was resolved.

**Comment by MelissaGraham** [comment] 2023-07-17 21:50
Luisa confirmed that the login issues persist. 

@lluisa11, when was the last time you successfully accessed the RSP and worked on your Notebook? If it was prior to Feb 2023, before the switch to the new identity management system, then I can delete your new account so you can try again, and all of your old files in your home directory from before Feb 2023 will still be waiting for you. However, if you did successfully access the RSP with your new account after Feb 2023, and you have things saved there, then I'm not sure I should delete your account.

**Comment by MelissaGraham** [comment] 2023-10-05 19:52
I contacted Luisa again via email today.

Luisa confirmed via email that the issue persists, and provided this screenshot.

![0](https://github.com/rubin-dp0/Support/assets/13826801/d9b74b1f-b1fb-4c28-8436-99900aff9634)

But that is a new account sign-up page at id.lsst.cloud, not a log-in page at data.lsst.cloud. And at upper left it appears that Luisa is already signed in. This error would be the natural result of attempting to make a duplicate account.

Recommended actions for Luisa:
1) At id.lsst.cloud (the page shown in the screenshot) click on the user name at upper right and then choose to logout.
2) Go to data.lsst.cloud. If your username appears at upper right, logout. 
3) At data.lsst.cloud, click at upper right where it says Log In. Select your identity provider, which I can see for California Polytechnic State University-San Luis Obispo. Use your calpoly credentials to log in.
4) If 3 is successful, you will be redirected to data.lsst.cloud and your username will appear at upper right. You can now choose to enter the Portal or Notebook Aspect.

Luisa please report back here whether that has worked or not at your earliest convenience. If it did not work, please answer the questions in the post above to help us figure out next steps.

**Comment by MelissaGraham** [comment] 2023-11-27 17:29
Emailed @lluisa11 today to check in on the recommended actions.

**Comment by ekosmac** [comment] 2024-04-17 18:20
I am also experiencing this same bug with my account after having it approved.

**Comment by MelissaGraham** [comment] 2024-04-18 14:48
Hi Emily (@ekosmac), did you try the four steps that are listed as "Recommended actions for Luisa"? I can see from your first screenshot, at upper right, that you are logged in at id.lsst.cloud, and step 1 is logout there. If you haven't yet, can you try those steps and report back?

**Comment by ekosmac** [comment] 2024-04-18 17:00
Hi Melissa, I did run through Recommended actions for Luisa, and the same
issue persists. I start from data.lsst.cloud and it sends me to that page.

**Comment by frossie** [comment] 2024-04-19 19:06
@ekosmac please try again now and let us know. 

Technical explanation for the record:

The system we use sends the user an email during the registration process asking them to confirm their account creation. Importantly, this is not over at that point; the user is directed to our system to give us some further information, such as which username they are requesting. Our systems then use that information to provision the user's account in the Rubin Science Platform.

What happened specifically with Emily's registration is that her institution uses some email security software to click on email links before the email is delivered to the user. This meant that the account was confirmed, BUT since Emily did not click the button herself she was not given the chance to complete the rest of the information, and so our system never got a chance to provision her RSP account, leaving her account in a half-baked state.

We have manually kicked off the provisioning process for Emily (we chose your github username as your RSP username - hope that was okay). 

The team supporting the identity manager software that we use (CILogon) has been made aware of this and in a future version of the software they will replace the current process with one that can be robust against software that clicks on email links on behalf of their users, now that we know that is a thing.

**Comment by MelissaGraham** [comment] 2024-06-05 22:51
This issue appears to be resolved so I am closing it. @ekosmac and @lluisa11, if you have any new issues please do open a new issue, anytime.

**Closed by MelissaGraham** 2024-06-05 22:51 UTC
Labels: RSP Authentication
